### ISSUE TITLE
Multiple Entry Points are not supported

### ISSUE THREAD

**Issue by storm1ng** [Permutatrix/rollup-plugin-hypothetical#12] opened 2019-03-06 12:24 UTC
When we use [multiple entry points](https://rollupjs.org/guide/en#input) as described in the docs then this plugin will throw the following error:
>[!] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

**Comment by lemmabit** [comment] 2021-08-28 21:31
I can't reproduce this, and I've added a test that the plugin works with multiple entry points. It may have been fixed by a change in Rollup's behavior. I'm closing this issue because of its age, but feel free to reopen it.

**Closed as completed by lemmabit** 2021-08-28 21:31 UTC
